version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./symfony:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/dafault.conf
    ports:
      - "8000:80"
    depends_on:
      - php
      - mariadb

  php:
    container_name: php
    build:
      context: ./php
    volumes:
      - ./symfony:/var/www/symfony
    ports:
      - "9000:9000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6.3-focal
    command: ["--default-authentication-plugin=mysql_native_password"]
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: docs_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3300:3306"
    volumes:
      - ./mariadb:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: pass
